### ISSUE TITLE
Type generation broken

### ISSUE THREAD

**Issue by wolfy1339** [octokit/octokit-next.js#101]
Due to the update of  `openapi-typescript` in #100, the type generation broke 

To remedy this, I propose we dry-run the type generation process whenever there's an update to `openapi-typescript`

See the logs:
```
file:///home/runner/work/octokit-next.js/octokit-next.js/node_modules/openapi-typescript/dist/load.js:141
    walk(options.schemas[schemaID].schema, (rawNode, nodePath) => {
                                   ^

TypeError: Cannot read properties of undefined (reading 'schema')
    at load (file:///home/runner/work/octokit-next.js/octokit-next.js/node_modules/openapi-typescript/dist/load.js:141:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async load (file:///home/runner/work/octokit-next.js/octokit-next.js/node_modules/openapi-typescript/dist/load.js:187:5)
    at async openapiTS (file:///home/runner/work/octokit-next.js/octokit-next.js/node_modules/openapi-typescript/dist/index.js:37:5)
    at async run (file:///home/runner/work/octokit-next.js/octokit-next.js/scripts/types-openapi/update.js:91:7)
```

https://github.com/octokit/octokit-next.js/actions/runs/3430908885/jobs/5718425041

**Comment by wolfy1339** [comment]
There seems to be other users that are having the same issue.
https://github.com/drwpow/openapi-typescript/issues/975

**Comment by wolfy1339** [comment]
It seems that the OpenAPI Update workflow should already cover this, as it is triggered by renovate branches.

There really should be a better way to make sure this doesn't happen again.

**Comment by kfcampbell** [comment]
Oh no! I'm sorry, what a hassle. 

- Should we revert #100? 
- I wonder if the build was skipped because of [this line](https://github.com/octokit/octokit-next.js/blob/main/.github/workflows/openapi-update.yml#L19) in the workflow. Perhaps we should consider broadening those conditions?

**Comment by wolfy1339** [comment]
No worries, it happens to the best of us :laughing: 

- It seems wise to revert #100 in the meantime
- From what I can work out, those conditions shouldn't be necessary.

On another note, the labels seem out of date in the workflow

**Comment by wolfy1339** [comment]
This will be fixed in https://github.com/drwpow/openapi-typescript/pull/977

**Comment by wolfy1339** [comment]
I've run into another issue, it doesn't seem to respect `"nullable": true` anymore

**Comment by wolfy1339** [comment]
The previous issue, was fixed. https://github.com/drwpow/openapi-typescript/pull/983
Current blocker: https://github.com/drwpow/openapi-typescript/issues/984
